package com.brilarisoft.lamuertapokerintelligence.domain.rule;

public enum RuleConditionType {
    HERO_WAS_PREFLOP_AGGRESSOR,
    VILLAIN_WAS_PREFLOP_AGGRESSOR,
    VILLAIN_CHECKED_TO_HERO,
    HERO_BET_CURRENT_STREET,
    VILLAIN_RAISED_HERO_BET,
    HERO_FACING_SECOND_BARREL,
    HERO_FACING_THIRD_BARREL,
    CURRENT_STREET_BET_COUNT,
    CURRENT_STREET_RAISE_COUNT,
    LINE_SIGNATURE,
    HERO_STRATEGY_LEGEND,
    FACING_ACTION_TYPE,
    CURRENT_ACTOR,
    POT_SIZE_BB,
    EFFECTIVE_STACK_BB,
    HERO_POSITION,
    VILLAIN_POSITION,
    SCENARIO_TYPE,
    STREET,
    HERO_HAND_CODE
}
